# Generated by Django 5.1 on 2024-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='blog_posts',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hashtags',
            field=models.ManyToManyField(to='blog.hashtag'),
        ),
    ]
