# Generated by Django 5.1 on 2024-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='rating',
            new_name='negative_rating',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='positive_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=45)),
                ('blog_posts', models.ManyToManyField(to='blog_post_app.blogpost')),
            ],
        ),
    ]
