# Generated by Django 5.1 on 2024-08-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPostVoting',
            new_name='BlogPostVote',
        ),
    ]
