# Generated by Django 5.1 on 2024-08-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0004_delete_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
