# Generated by Django 5.1 on 2024-08-13 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0005_remove_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 14, 20, 32, 214663), verbose_name='the date user is registered'),
        ),
    ]
