# Generated by Django 5.1 on 2024-08-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0008_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
